services:
  bot:
    build:
      context: .
      no_cache: true
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - bot-database:/app/database
      - bot-leaderboard:/app/leaderboard
    networks:
      - klopfer-network

volumes:
  bot-database:
    driver: local
  bot-leaderboard:
    driver: local

networks:
  klopfer-network:
    driver: bridge